/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import conexiones.Procedimientos;
import conexiones.Conexiones;
import conexiones.Limitar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.mediticket.controllers.RolJpaController;
import org.mediticket.controllers.RolusuarioJpaController;
import org.mediticket.controllers.UsuarioJpaController;
import org.mediticket.entities.Rol;
import org.mediticket.entities.Rolusuario;
import org.mediticket.entities.RolusuarioPK;
import org.mediticket.entities.Usuario;

/**
 *
 * @author josuericardo
 */
public class FrmLogin extends javax.swing.JFrame {
    /*Objetos Globales*/
        /*Rolusuario person = new Rolusuario();
        ArrayList <Object> listaRolesAsignados = new ArrayList <Object>();*/
    UsuarioJpaController usuarioRegistrado = new UsuarioJpaController();
    RolJpaController rolRegistrado = new RolJpaController();
    RolusuarioJpaController rolUsuariRegistrado = new RolusuarioJpaController();
    Conexiones conexion = new Conexiones();
    static ResultSet buscar;
    /*Usuario admin =new Usuario();
    Rol roles = new Rol(); 
    Rolusuario rolUser = new Rolusuario();*/
    
    
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        //creacionUser();
        //cargarCombo();
        bloqueoIngreso(false);
        limitarr();
        /*Botones*/
        /*btningresar.setEnabled(false);*/
        /*Fondo*/
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("../Imagenes/fondo8.png"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }
  public void limitarr(){
        txtusuario.setDocument(new Limitar(txtusuario,10));
        txtpass.setDocument(new Limitar(txtpass, 8));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblIP = new javax.swing.JLabel();
        txtdireccionIP = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jpnEntrada = new javax.swing.JPanel();
        lblusuario2 = new javax.swing.JLabel();
        lblcontasenia1 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btningresar = new javax.swing.JButton();
        cmbtipo = new javax.swing.JComboBox<>();
        lblusuario3 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/epn_converted.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dirección Servidor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Fax", 0, 12))); // NOI18N
        jPanel1.setOpaque(false);

        lblIP.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblIP.setText("IP");

        txtdireccionIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionIPActionPerformed(evt);
            }
        });

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIP)
                        .addGap(18, 18, 18)
                        .addComponent(txtdireccionIP, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVerificar)
                        .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdireccionIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIP))
                .addGap(18, 18, 18)
                .addComponent(btnVerificar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel3.setText("ESCUELA POLITÉCNICA NACIONAL ");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel4.setText("ESCUELA DE FORMACIÓN DE TECNOLOGOS");

        jpnEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Bienvenido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Fax", 0, 12))); // NOI18N
        jpnEntrada.setOpaque(false);

        lblusuario2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblusuario2.setText("Usuario:");

        lblcontasenia1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblcontasenia1.setText("Contraseña:");

        btningresar.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        btningresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entrar_converted (1).png"))); // NOI18N
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        cmbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipoActionPerformed(evt);
            }
        });

        lblusuario3.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblusuario3.setText("Modo:");

        javax.swing.GroupLayout jpnEntradaLayout = new javax.swing.GroupLayout(jpnEntrada);
        jpnEntrada.setLayout(jpnEntradaLayout);
        jpnEntradaLayout.setHorizontalGroup(
            jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnEntradaLayout.createSequentialGroup()
                .addGroup(jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnEntradaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcontasenia1)
                            .addComponent(lblusuario2)
                            .addComponent(lblusuario3))
                        .addGap(18, 18, 18)
                        .addGroup(jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(txtusuario))))
                    .addGroup(jpnEntradaLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btningresar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnEntradaLayout.setVerticalGroup(
            jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusuario3))
                .addGap(18, 18, 18)
                .addGroup(jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuario2)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontasenia1)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btningresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Dirección IP");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
        String cedula = txtusuario.getText();
        String password = txtpass.getText();
        
        if(usuarioRegistrado.findUsuario(cedula)!=null){
            Usuario user = usuarioRegistrado.findUsuario(cedula);
            RolusuarioPK roluser = new RolusuarioPK(cmbtipo.getSelectedIndex()+1, cedula);
            if(rolUsuariRegistrado.findRolusuario(roluser)!=null){
                if(user.getPassword().equals(password)){
                    if(cmbtipo.getSelectedIndex()==0){
                        System.out.println("Ingreso correctamente");
                        FrmAdministrador a1 = new FrmAdministrador();
                        a1.setVisible(true);
                        this.setVisible(false);
                    }else{
                        System.out.println("Ingreso correctamente");
                        /*FrmUsuario u1 = new FrmUsuario();
                        u1.setVisible(true);
                        this.setVisible(false);*/
                         try{
                                                String cedu= txtusuario.getText();
                                                Procedimientos.EncontrarPaciente(cedu);
                                                /*FrmUsuario.txtpass2.setText("");
                                                FrmUsuario.txtapellidos2.setText("");
                                                FrmUsuario.txtcedula2.setText("");
                                                FrmUsuario.txtdireccion2.setText("");
                                                FrmUsuario.txtespecialidad2.setText("");
                                                FrmUsuario.txtnombre2.setText("");
                                                FrmUsuario.txttelefono2.setText("");

                                                FrmUsuario.txtapellidos2.requestFocus();
                                                FrmUsuario.txtcedula2.requestFocus();
                                                FrmUsuario.txtdireccion2.requestFocus();
                                                FrmUsuario.txtespecialidad2.requestFocus();
                                                FrmUsuario.txtnombre2.requestFocus();
                                                FrmUsuario.txtpass2.requestFocus();
                                                FrmUsuario.txttelefono2.requestFocus();*/

                                                buscar= conexiones.Conexiones.Consulta("select * from USUARIO");
                                                while(buscar.next()){
                                                    if(buscar.getString(1).equals(cedu)){
                                                        FrmUsuario u1 = new FrmUsuario();
                                                        u1.setVisible(true);
                                                        this.setVisible(false);
                                                        //JOptionPane.showMessageDialog(null, "datos encontrados");
                                                        FrmUsuario.txtcedula2.setText(buscar.getString(1));
                                                        FrmUsuario.txtnombre2.setText(buscar.getString(2));
                                                        FrmUsuario.txtapellidos2.setText(buscar.getString(3));
                                                        FrmUsuario.txttelefono2.setText(buscar.getString(4));
                                                        FrmUsuario.txtpass2.setText(buscar.getString(5));
                                                        FrmUsuario.txtespecialidad2.setText(buscar.getString(6));
                                                        FrmUsuario.txtdireccion2.setText(buscar.getString(7));
                                                             
                                                    }
                                                }
                                                //JOptionPane.showMessageDialog(null, "No se encontro ningun resultado");
                                                   System.out.println("Ingreso correctamente");
                                            }catch(SQLException e){
                                            }
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Verifique su contraseña","Contraseña Incorrecta",JOptionPane.WARNING_MESSAGE);
                    System.out.println(cmbtipo.getSelectedItem()+user.getNombre()+"Contraseña incorrecta");
                    limpiar();
                }
                
            }else{
                System.out.println(user.getNombre()+" No es "+cmbtipo.getSelectedItem());
                JOptionPane.showMessageDialog(rootPane,"Usuario no registrado en esta categoría","Categoría",JOptionPane.WARNING_MESSAGE);
                limpiar();
            }
        }else{
            System.out.println("Usuario no existe");
            JOptionPane.showMessageDialog(rootPane,"Usuario incorrecto","Error",JOptionPane.ERROR_MESSAGE);
            limpiar();
        }
    }//GEN-LAST:event_btningresarActionPerformed

    private void cmbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtipoActionPerformed

    private void txtdireccionIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionIPActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        String direccionIP = txtdireccionIP.getText();
            conexion = new Conexiones(direccionIP);
            //ConnectionProperties conexion = new ConnectionProperties(txtIP.getText());
            
            if(!"".equals(direccionIP)){
                conexion.getConexion();
                if(conexion.isIngreso() == true){
                    bloqueoIngreso(true);
                    txtdireccionIP.setEnabled(false);
                    btnVerificar.setEnabled(false);
                    usuarioRegistrado = new UsuarioJpaController(direccionIP);
                    rolRegistrado = new RolJpaController(direccionIP);
                    rolUsuariRegistrado = new RolusuarioJpaController(direccionIP);
                    creacionUser();
                    cargarCombo();
                }else{
                    txtdireccionIP.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Ingrese una dirección del servidor","Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnVerificarActionPerformed
    public void creacionUser(){
        if(usuarioRegistrado.getUsuarioCount()==0 && rolRegistrado.getRolCount()==0 
                && rolUsuariRegistrado.getRolusuarioCount()==0){
            Usuario user =new Usuario("1724449325","Josué","Cando","2606591","josue","Técnico","Loma de Puengasí");
            Rol rol1 = new Rol(1,"Administrador");
            Rol rol2 = new Rol(2,"Doctor");
            Rol rol3 = new Rol(3,"Enfermera");
            /*rolUser1.setFechacreacion("2017/06/25");*/
            try {
                    usuarioRegistrado.create(user);
                    rolRegistrado.create(rol1);
                    rolRegistrado.create(rol2);
                    rolRegistrado.create(rol3);
                    Procedimientos.EntradaRolUsuario(1,"1724449325","2017/06/25"); 
                    JOptionPane.showMessageDialog(rootPane,"El cliente se ha registrado con "+
                            "éxito","Información",JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                    /*el emtodo ex.getmesaer me entrega el tipo de error que se produjo*/
                    JOptionPane.showMessageDialog(rootPane,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    public void cargarCombo(){
        for (int i = 0; i < rolRegistrado.getRolCount(); i++) {
            Rol rol = new Rol();
            rol = rolRegistrado.findRol(i+1);
            cmbtipo.insertItemAt(rol.getNombrerol(),i);
        }
    }
    public void limpiar(){
        //txtdireccionIP.setEnabled(true);
        txtusuario.setText("");
        txtpass.setText("");
    }
    public void bloqueoIngreso(boolean bloquear){
        cmbtipo.setEnabled(bloquear);
        txtpass.setEnabled(bloquear);
        txtusuario.setEnabled(bloquear);
        btningresar.setEnabled(bloquear);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btningresar;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpnEntrada;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblcontasenia1;
    private javax.swing.JLabel lblusuario2;
    private javax.swing.JLabel lblusuario3;
    private javax.swing.JTextField txtdireccionIP;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

}
